### PR TITLE
verification request for owning Polkadot address

### PR DESCRIPTION
**Pull request by aircable**
1: email ownership through Github
2: web page ownership through .well-known file

requestJudgement sent too.

### CODE REVIEW

**Review by sorpaas — CHANGES_REQUESTED** [review]
The identity currently set on-chain contains a "legal name" field. To verify the legal name, the only supported method at this moment is through Estonia eIDs. https://polkaregistry.org/docs/procedure/#estonia-eid-proof
Alternatively, you can remove the legal name field set on-chain.

**Comment by aircable** [comment]
I need to change the set_identity extrinsic. Do I have to kill_identity first, or just a new set_identity?

**Comment by sorpaas** [comment]
@aircable Just call `set_identity`. You don't have to `kill_identity` first.

**Comment by aircable** [comment]
did that work? 
EID: 8047645-3 Block 8047645

**Comment by sorpaas** [comment]
Unfortunately both appear to be invalid:

* The gist should contain a signature in the end. sr25519 signatures are 64 bytes, but the supplied is much shorter.
* The website verification is invalid because it does not contain a signature. See https://polkaregistry.org/docs/procedure/#website-proof for the format needed.

**Comment by aircable** [comment]
this is what I did: see screenshot. I copied the encoded call hash. Or do you need the full encoded data??
Screenshot from 2021-12-08 10-56-35

**Comment by sorpaas** [comment]
@aircable That's the extrinsic tab which is not for generating signatures!

Go to "developer" - "sign and verify" - "sign message".

**Comment by aircable** [comment]
oops, didn't know.
Fixed both files. Ok now?

**Review by sorpaas — APPROVED** [review]
All verifications passed. Cheers!
The on-chain judgement will be added shortly.

Please keep your proofs public and don't delete them. Polkaregistry is designed to be trustless, and this allows others to re-verify them.

**Comment by aircable** [comment]
will do, thank you very much for helping me with this!

**Pull request merged**
